### ISSUE TITLE
install_vault.sh fails on copy vault to /usr/local/bin on Linux Mint 18.3

### ISSUE THREAD

**Issue by ultiweb-zz** [immutability-io/immutability-project#1]
## Detailed Description

The install script fails to copy the vault executable to /usr/local/bin/ and fails soon after because after that mv failure the script apparently depends on the vault executable being in the correct place. The dependency on jq isn't listed in the instructions either, or I missed it somehow. 

Here is where the script fails without trying to workaround the issue.
mv: cannot create regular file '/usr/local/bin/vault': Permission denied
./install_vault.sh: line 122: vault: command not found
./install_vault.sh: line 127: jq: command not found
▶ ERROR For user "./ultiweb_VAULT_TOKEN.txt": Invalid key-value identity: ./ultiweb_VAULT_TOKEN.txt
Keybase encryption failed!

I tried running the script with sudo but that fails also with an error stating that the script can't be run with root permissions.

I've installed jq and moved vault to /usr/local/bin, removed ~/etc/vault.d, re-cloned the repo and rerun the script and it runs into another issue. 
mv: replace '/usr/local/bin/vault', overriding mode 0755 (rwxr-xr-x)? n
Error initializing: Put https://localhost:8200/v1/sys/init: dial tcp 127.0.0.1:8200: getsockopt: connection refused

This last error is not a firewall issue. I disabled the firewall completely and same error after deleting, re-cloning, etc. I'm stuck here as far as working around the issues.

## Context

I want to run through your vault tutorial on Linux. :-) https://www.hashicorp.com/blog/using-vault-to-build-an-ethereum-wallet

Everyone on Linux would be able to run vault on Linux/Ubuntu/Mint, at least this version of the repo.
## Possible Implementation

Run the mv command with sudo, which should ask me for my password. I'm not sure how to implement it but I have run bash scripts that probably run a subshell and use sudo, then go back to the spawning shell.
## Your Environment

* Version used: 79f440b refs/heads/master@{0}: clone: from https://github.com/immutability-io/immutability-project.git
* Environment name and version (e.g. Chrome 39, node.js 5.4): Linux [hostname] 4.13.0-36-generic #40~16.04.1-Ubuntu SMP Fri Feb 16 23:25:58 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
* Operating System and version (desktop or mobile): laptop/desktop
* Link to your project:

**Comment by cypherhat** [comment]
Looks down in shame. I'll fix it - gonna rebuild my Docker images too to stay up to date.

**Comment by cypherhat** [comment]
I patched the script. Please verify that this works for you.
